# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Контекст',
                'verbose_name_plural': 'Контексты',
            },
        ),
        migrations.CreateModel(
            name='ContextGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Группировка контекстов',
                'verbose_name_plural': 'Группировки контекстов',
            },
        ),
        migrations.CreateModel(
            name='ContextSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
            options={
                'verbose_name': 'Набор контекстов для слова',
                'verbose_name_plural': 'Наборы контекстов для слов',
            },
        ),
        migrations.CreateModel(
            name='Testee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Испытуемый',
                'verbose_name_plural': 'Испытуемые',
            },
        ),
        migrations.AddField(
            model_name='contextgroup',
            name='context_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.ContextSet'),
        ),
        migrations.AddField(
            model_name='contextgroup',
            name='contexts',
            field=models.ManyToManyField(to='survey.Context'),
        ),
        migrations.AddField(
            model_name='contextgroup',
            name='testee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Testee'),
        ),
        migrations.AddField(
            model_name='context',
            name='context_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.ContextSet'),
        ),
        migrations.AlterUniqueTogether(
            name='contextgroup',
            unique_together=set([('testee', 'context_set')]),
        ),
        migrations.AlterModelOptions(
            name='contextset',
            options={'ordering': ['order'], 'verbose_name': 'Набор контекстов для слова', 'verbose_name_plural': 'Наборы контекстов для слов'},
        ),
        migrations.AddField(
            model_name='contextset',
            name='order',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
