# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='finished',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='started',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
