# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20160813_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['finished'], 'verbose_name': 'Испытуемый', 'verbose_name_plural': 'Испытуемые'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='finished',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
