# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20160813_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
    ]
