# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20160817_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='source',
            field=models.TextField(blank=True, default=''),
        ),
    ]
