# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_participant_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextset',
            name='is_filler',
            field=models.BooleanField(default=False),
        ),
    ]
