# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_contextset_is_filler'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cs_to_group',
            field=models.ManyToManyField(to='survey.ContextSet'),
        ),
    ]
