# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20180717_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextset',
            name='derivation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contextset',
            name='group',
            field=models.TextField(default=''),
        ),
    ]
